#!/usr/bin/env ruby
# frozen_string_literal: true

require 'gdm'

if GDM::Platform.linux?
  puts("starting #{GDM::Platform.linux_headless_filename}")
  system(GDM::Platform.linux_headless_filename, *ARGV)
end
