#!/usr/bin/env ruby
# frozen_string_literal: true

require 'gdm'

if GDM::Platform.linux?
  puts("starting #{GDM::Platform.linux_server_filename}")
  system(GDM::Platform.linux_server_filename, *ARGV)
end
